### ISSUE TITLE
Design and create mouseover icons for draw mode

### ISSUE THREAD

**Issue by nkprasad12** [nkprasad12/dnd#138]
We want to create some special mouse icons for draw mode:

1. When the user is in draw mode, we want a special icon for this (pencil or paintbrush)
2. When the user is in selection mode, to be able to select and move / copy / delete drawn items figures, we want a special icon for this
3. For straight lines, when the user has an anchor down, and the next click will create a straight line from the anchor point to the clicked point, we need to signify this.

**Comment by Kaninapo** [comment]
[drawmouseover.zip](https://github.com/nkprasad12/dnd/files/6207122/drawmouseover.zip)
