### ISSUE TITLE
Create Icons for Panel Menu

### ISSUE THREAD

**Issue by nkprasad12** [nkprasad12/dnd#139]
Currently, we have a tabbed panel menu with:

- "Game Board" which is the main game board
- "Board Tools" which allows creation of new boards or editing characteristics of existing boards.

Ideally, we would want to replace these with icons. Quick ideas:

Game Board might be a "Home" icon, or something representing DnD, or games, etc...
Board Tools would be something that conveys the idea of "Editing"

In addition, we also want an icon for "Settings" eventually.

**Comment by Kaninapo** [comment]
[panelmenu.zip](https://github.com/nkprasad12/dnd/files/6207118/panelmenu.zip)
