### ISSUE TITLE
Add smarter "complete" functionality

### ISSUE THREAD

**Issue by ReidAnderson** [nkprasad12/dnd#96]
I went through and basically rerolled everything from the last session for Eberk. Everything looks like it was working, the only thing that I found is that Avrae in discord was able to identify which rapier I was talking about when I did `!attack rapier`, but dnd could not.

![image](https://user-images.githubusercontent.com/1248890/110217747-742b3d00-7e7b-11eb-8829-0b8a6e409f69.png)

**Comment by nkprasad12** [comment]
In the above example we see that we couldn't resolve "Luck Blade Rapier" from "Rapier", since the completer is strictly a prefix based completer. Ideally in the future we would be able to handle such cases and potentially fuzzy matching (like typos) as well.
